In [27]:
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [12]:
data = pd.read_csv('labelled.csv')


In [13]:
data

Unnamed: 0  age  fnlwgt  educational-num  gender  capital-gain  \
0               0   25  226802                7       1             0   
1               5   34  198693                6       1             0   
2               8   24  369667               10       0             0   
3              12   26   82091                9       0             0   
4              16   20  444554               10       1             0   
...           ...  ...     ...              ...     ...           ...   
14707       48818   30  345898                9       1             0   
14708       48829   65   99359               15       1          1086   
14709       48834   32  116138               14       1             0   
14710       48836   22  310152               10       1             0   
14711       48840   22  201490                9       1             0   

       capital-loss  hours-per-week  income  Federal-gov  ...  \
0                 0              40       1            0  ...   
1                 0              30       1            0  ...   
2                 0              40       1            0  ...   
3                 0              39       1            0  ...   
4                 0              25       1            0  ...   
...             ...             ...     ...          ...  ...   
14707             0              46       1            0  ...   
14708             0              60       1            0  ...   
14709             0              11       1            0  ...   
14710             0              40       1            0  ...   
14711             0              20       1            0  ...   

       Handlers-cleaners  Machine-op-inspct  Other-service  Priv-house-serv  \
0                      0                  1              0                0   
1                      0                  0              1                0   
2                      0                  0              1                0   
3                      0                  0              0                0   
4                      0                  0              1                0   
...                  ...                ...            ...              ...   
14707                  0                  0              0                0   
14708                  0                  0              0                0   
14709                  0                  0              0                0   
14710                  0                  0              0                0   
14711                  0                  0              0                0   

       Prof-specialty  Protective-serv  Sales  Tech-support  Transport-moving  \
0                   0                0      0             0                 0   
1                   0                0      0             0                 0   
2                   0                0      0             0                 0   
3                   0                0      0             0                 0   
4                   0                0      0             0                 0   
...               ...              ...    ...           ...               ...   
14707               0                0      0             0                 0   
14708               1                0      0             0                 0   
14709               0                0      0             1                 0   
14710               0                1      0             0                 0   
14711               0                0      0             0                 0   

       cluster  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
14707        1  
14708        1  
14709        1  
14710        1  
14711        1  

[14712 rows x 44 columns]

# baseline decision tree

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Split the data into features and labels
X = data.drop(columns=['income'])
y = data['income']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the decision tree model
model = DecisionTreeClassifier(random_state=42)

# Train the model
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Calculate accuracy on the test set
accuracy = accuracy_score(y_test, y_pred)
print(" Within cluster Test Accuracy:", accuracy)

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate other scores (precision, recall, F1 score, support)
report = classification_report(y_test, y_pred, target_names=['<=50K', '>50K'])
print("Classification Report:")
print(report)


 Within cluster Test Accuracy: 0.946313285762827
Confusion Matrix:
[[  55   70]
 [  88 2730]]
Classification Report:
              precision    recall  f1-score   support

       <=50K       0.38      0.44      0.41       125
        >50K       0.97      0.97      0.97      2818

    accuracy                           0.95      2943
   macro avg       0.68      0.70      0.69      2943
weighted avg       0.95      0.95      0.95      2943



In [17]:
unlabel_test = pd.read_csv('unlabelled_test.csv')

X = unlabel_test.drop(columns=['income'])
y = unlabel_test['income']

y_pred = model.predict(X)
accuracy = accuracy_score(y, y_pred)
print("Unlabelled data Test Accuracy:", accuracy)



Unlabelled data Test Accuracy: 0.7058341527368076


/usr/lib64/python3.11/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


# baseline random forest

In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Split the data into features and labels
X = data.drop(columns=['income'])
y = data['income']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Calculate accuracy on the test set
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate other scores (precision, recall, F1 score, support)
report = classification_report(y_test, y_pred, target_names=['<=50K', '>50K'])
print("Classification Report:")
print(report)

Test Accuracy: 0.9724770642201835
Confusion Matrix:
[[  48   77]
 [   4 2814]]
Classification Report:
              precision    recall  f1-score   support

       <=50K       0.92      0.38      0.54       125
        >50K       0.97      1.00      0.99      2818

    accuracy                           0.97      2943
   macro avg       0.95      0.69      0.76      2943
weighted avg       0.97      0.97      0.97      2943



In [19]:
unlabel_test = pd.read_csv('unlabelled_test.csv')

X = unlabel_test.drop(columns=['income'])
y = unlabel_test['income']

y_pred = model.predict(X)
accuracy = accuracy_score(y, y_pred)
print("Unlabelled data Test Accuracy:", accuracy)



Unlabelled data Test Accuracy: 0.70671910848902


/usr/lib64/python3.11/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


# baseline logistic regression

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Split the data into features and labels
X = data.drop(columns=['income'])
y = data['income']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the Logistic Regression model
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Calculate accuracy on the test set
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate other scores (precision, recall, F1 score, support)
report = classification_report(y_test, y_pred, target_names=['<=50K', '>50K'])
print("Classification Report:")
print(report)

Test Accuracy: 0.9660210669384981
Confusion Matrix:
[[  38   87]
 [  13 2805]]
Classification Report:
              precision    recall  f1-score   support

       <=50K       0.75      0.30      0.43       125
        >50K       0.97      1.00      0.98      2818

    accuracy                           0.97      2943
   macro avg       0.86      0.65      0.71      2943
weighted avg       0.96      0.97      0.96      2943



In [23]:
unlabel_test = pd.read_csv('unlabelled_test.csv')

X = unlabel_test.drop(columns=['income'])
y = unlabel_test['income']

y_pred = model.predict(X)
accuracy = accuracy_score(y, y_pred)
print("Unlabelled data Test Accuracy:", accuracy)


Unlabelled data Test Accuracy: 0.34424778761061947


/usr/lib64/python3.11/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [31]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Split the data into features and labels
X = data.drop(columns=['income'])
y = data['income']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the neural network model
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(X_train_scaled.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train, epochs=50, batch_size=64, validation_split=0.1)

# Evaluate the model on the test set
y_pred = model.predict(X_test_scaled)
y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions (0 or 1)
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate other scores (precision, recall, F1 score, support)
report = classification_report(y_test, y_pred, target_names=['<=50K', '>50K'])
print("Classification Report:")
print(report)


Epoch 1/50
166/166 [==============================] - 1s 1ms/step - loss: 0.2048 - accuracy: 0.9435 - val_loss: 0.1270 - val_accuracy: 0.9507
Epoch 2/50
166/166 [==============================] - 0s 962us/step - loss: 0.1183 - accuracy: 0.9568 - val_loss: 0.1193 - val_accuracy: 0.9575
Epoch 3/50
166/166 [==============================] - 0s 1ms/step - loss: 0.1103 - accuracy: 0.9611 - val_loss: 0.1166 - val_accuracy: 0.9601
Epoch 4/50
166/166 [==============================] - 0s 988us/step - loss: 0.1061 - accuracy: 0.9619 - val_loss: 0.1181 - val_accuracy: 0.9609
Epoch 5/50
166/166 [==============================] - 0s 979us/step - loss: 0.1038 - accuracy: 0.9620 - val_loss: 0.1207 - val_accuracy: 0.9609
Epoch 6/50
166/166 [==============================] - 0s 961us/step - loss: 0.1018 - accuracy: 0.9640 - val_loss: 0.1242 - val_accuracy: 0.9584
Epoch 7/50
166/166 [==============================] - 0s 986us/step - loss: 0.0999 - accuracy: 0.9632 - val_loss: 0.1256 - val_accuracy: 0.9

In [29]:
unlabel_test = pd.read_csv('unlabelled_test.csv')

X = unlabel_test.drop(columns=['income'])
y = unlabel_test['income']

y_pred = model.predict(X)
accuracy = accuracy_score(y, y_pred)
print("Unlabelled data Test Accuracy:", accuracy)

# Calculate confusion matrix
cm = confusion_matrix(y, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate other scores (precision, recall, F1 score, support)
report = classification_report(y, y_pred, target_names=['<=50K', '>50K'])
print("Classification Report:")
print(report)


954/954 [==============================] - 1s 582us/step
Unlabelled data Test Accuracy: 0.662962962962963
Confusion Matrix:
[[  221 10282]
 [    1 20006]]
Classification Report:
              precision    recall  f1-score   support

       <=50K       1.00      0.02      0.04     10503
        >50K       0.66      1.00      0.80     20007

    accuracy                           0.66     30510
   macro avg       0.83      0.51      0.42     30510
weighted avg       0.78      0.66      0.54     30510

